### ISSUE TITLE
is this project active? 

### ISSUE THREAD

**Issue by SarasArya** [faceleg/angular-busy-plus#1]
Hey, I saw that your comment on angular-busy issue. Seems like you are an active author. I am facing an issue here. The backdrop is not coming for me. To highlight the issue.I have created a [plunk](https://plnkr.co/edit/m5QqRDx0dzyPfXPzDn8K?p=preview) Please have a look at it.

**Comment by faceleg** [comment]
Probably the request was over too quickly for the backdrop to display, see https://plnkr.co/edit/fbPrfLb0Ks7UQ0WR6HCI?p=preview
