### ISSUE TITLE
Set up Travis

### ISSUE THREAD

**Issue by jphustman** [faceleg/angular-busy-plus#4]
@Faceleg if you set up https://travis-ci.org/faceleg/angular-busy-plus it should be all set up to automatically run tests.

I've replaced grunt with gulp -- I didn't make any changes to the core angular-busy.js but the karma tests are failing right now - I am thinking about making a huge change and making everything that is 'angular-busy' to 'angular-busy-plus' -- 

Either way, now we have a 'develop' branch we can work in -- try it, pull it down then run '**gulp serve**'

**Comment by faceleg** [comment]
Done! Sorry for the delay
